In [9]:
from sklearn.preprocessing import StandardScaler
import matplotlib as pyplot
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [19]:
data=pd.read_csv('KNN_Dataset.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [20]:
not_zero=['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

In [21]:
for i in not_zero:
    data[i]=data[i].replace(0,np.NaN)
    mean=int(data[i].mean(skipna=True))
    data[i]=data[i].replace(np.NAN,mean)

In [22]:
x=data.iloc[:,0:8]
y=data.iloc[:,8]
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [23]:
print(x_train.shape,y_train.shape,y_test.shape,x_test.shape)
x_test

(614, 8) (614,) (154,) (154, 8)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
661            1    199.0           76.0           43.0    155.0  42.9   
122            2    107.0           74.0           30.0    100.0  33.6   
113            4     76.0           62.0           29.0    155.0  34.0   
14             5    166.0           72.0           19.0    175.0  25.8   
529            0    111.0           65.0           29.0    155.0  24.6   
..           ...      ...            ...            ...      ...   ...   
476            2    105.0           80.0           45.0    191.0  33.7   
482            4     85.0           58.0           22.0     49.0  27.8   
230            4    142.0           86.0           29.0    155.0  44.0   
527            3    116.0           74.0           15.0    105.0  26.3   
380            1    107.0           72.0           30.0     82.0  30.8   

     DiabetesPedigreeFunction  Age  
661                     1.394   22  
122                     0.404   23  
113                     0.391   25  
14                      0.587   51  
529                     0.660   31  
..                        ...  ...  
476                     0.711   29  
482                     0.306   28  
230                     0.645   22  
527                     0.107   24  
380                     0.821   24  

[154 rows x 8 columns]

In [24]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [27]:
print(x_train.shape,y_train.shape,y_test.shape,x_test.shape)
classifier=KNeighborsClassifier(p=2,n_jobs=11,metric='euclidean')
classifier.fit(x_test,y_test)

(614, 8) (614,) (154,) (154, 8)


KNeighborsClassifier(metric='euclidean', n_jobs=11)

In [28]:
y_predict=classifier.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [29]:
confusion_matrix(y_predict,y_test)

array([[95,  8],
       [12, 39]])

In [30]:
accuracy_score(y_predict,y_test)

0.8701298701298701

In [31]:
from sklearn import svm

In [32]:
svm=svm.SVC(kernel='linear',C=1)

In [33]:
svm.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [35]:
svm_predict=svm.predict(x_test)
svm_predict

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [39]:
print(confusion_matrix(svm_predict,y_test))
print(accuracy_score(svm_predict,y_test))

[[97 21]
 [10 26]]
0.7987012987012987
